language: node_js
node_js:
  - 0.10

services:
  - mongodb

env:
  global:
    - NODE_ENV=test

notifications:
  email:
    recipients:
      - kevin@vidigami.com

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"